name: Build artifacts

on:
  push:
#    branches:
#      - develop

env:
  NODE_VERSION: '10.x'   # Node 10 LTS

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: yarn
        run: yarn
      - name: yarn docs2
        working-directory: docs2
        run: yarn
      - name: yarn gatsby build
        working-directory: docs2
        run: yarn gatsby build
      - name: Publish docs artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Documentation
          path: docs2/public/**
          if-no-files-found: error
      - name: Use .NET Core 3.1 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Install dependencies
        working-directory: src
        run: dotnet restore
      - name: Build solution (release config)
        working-directory: src
        run: dotnet build --no-restore -c Release -p:NoWarn=CS1591 -p:VersionSuffix=${{ github.run_id }}
      - name: Pack solution (release config)
        working-directory: src
        run: dotnet pack --no-restore -c Release -p:VersionSuffix=${{ github.run_id }} -o out
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Nuget packages
          path: src/out/*.nupkg
#      - name: Publish Nuget packages to GitHub registry
#        working-directory: src
#        run: dotnet nuget push out/*.nupkg -s "myget-graphql-dotnet" -k ${{ secrets.GITHUB_TOKEN }}
